services:
  db:
    image: postgres:13-alpine
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ollama:
    image: ollama/ollama:latest
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  backend:
    build: ./backend
    restart: always
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - UPLOADS_DIR=/app/uploads
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - entropia_uploads:/app/uploads

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules

volumes:
  postgres_data:
  ollama_data:
  entropia_uploads:
  frontend_node_modules:
